apps/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views

# Custom imports
from users import views as user_views

app_name = "apps"

urlpatterns = [
    # main url's
    path("admin/", admin.site.urls),
    path("events/", include("events.urls", namespace="events")),
    path("submissions/", include("submissions.urls", namespace="submissions")),
    path("", include("events.urls", namespace="home")),
    # Registration and SignIn related
    path("register/", user_views.register, name="register"),
    path("login/", user_views.login_request, name="login"),
    path("logout/", user_views.logout_request, name="logout"),
    # Profile related
    path("profile/", user_views.show_profile, name="profile"),
    path("profile/edit/<int:pk>", user_views.student_update, name="edit_profile"),
    # Deactivation related
    path("deactivate/", user_views.deactivate, name="deactivate"),
    path("reactivate/", user_views.reactivate, name="reactivate"),
    # Password reset related
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<str:uidb64>/<str:token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("", views.event_list, name="event_list"),
    path("<int:pk>", views.event_detail, name="event_detail"),
    path("new", views.event_create, name="event_new"),
    path("edit/<int:pk>", views.event_update, name="event_update"),
    path("delete/<int:pk>", views.event_delete, name="event_delete"),
]

submissions/urls.py
from django.urls import path

from . import views

app_name = "submissions"

urlpatterns = [
    path("", views.submission_list, name="submission_list"),
    path("<int:pk>", views.submission_detail, name="submission_detail"),
    path("new/<int:event_pk>", views.submission_create, name="submission_new"),
    path("edit/<int:pk>", views.submission_update, name="submission_update"),
    path("delete/<int:pk>", views.submission_delete, name="submission_delete"),
    path("done/<int:pk>", views.submission_done, name="submission_done"),
    path("undone/<int:pk>", views.submission_undone, name="submission_undone"),
]

events/models.py
from django.db import models
from apps.models import ModelWithTimeStamp
from django.urls import reverse
from django.conf import settings
from users.models import Student

class Event(ModelWithTimeStamp):
    """ The Event model saves informations about a event, including its deadline """

    # every value is a tuple (actual_value, human_redable_value)
    QUALIS_CHOICES = (
        ("A1", "A1"),
        ("A2", "A2"),
        ("A3", "A3"),
        ("A4", "A4"),
        ("B1", "B1"),
        ("B2", "B2"),
        ("B3", "B3"),
        ("B4", "B4"),
        ("C", "C"),
        ("", "Does not apply"),
    )

    TYPE_CHOICES = (
        ("1", "Periodic"),
        ("2", "National Conference"),
        ("3", "International Conference"),
        ("4", "Journal"),
        ("4", "Workshops"),
        ("5", "Seminars"),
        ("6", "Others")
    )

    name = models.CharField(max_length=200)
    url = models.CharField(max_length=500, null=True, blank=True)
    qualis = models.CharField(max_length=10, choices=QUALIS_CHOICES)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, null=True, blank=True)
    deadline = models.DateField()
    

    def __str__(self):
        """Console representation of a Event"""
        return self.name

    def get_absolute_url(self):
        return reverse("event:event_edit", kwargs={"pk": self.pk})

submissions/models.py
from django.db import models
from users.models import Student
from events.models import Event
from apps.models import ModelWithTimeStamp

class Submission(ModelWithTimeStamp):
    ''' This model stores informations about academic event submissions '''
    STATUS_CHOICES = (
        ('0', "In Writting Process"),
        ("1", "Not submitted"),
        ("2", "Under Revision"),
        ("3", "Accepted"),
        ("4", "Rejected"),
    )

    students = models.ManyToManyField(Student, blank=False, related_name='submissions')

    event = models.ForeignKey(Event, on_delete=models.SET_NULL,  null=True, related_name='submissions')

    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='0')

    paper_acronym = models.CharField(max_length=100, blank=False) 

    paper_url = models.CharField(max_length=400, blank=True, null=True)

    presentation_url = models.CharField(max_length=400, blank=True, null=True)

    rebuttal_url = models.CharField(max_length=400, blank=True, null=True)

    # Checklist fields ( related to the progress bar )
    implementation_done = models.BooleanField(blank=False, default=False)
    paper_introduction_done = models.BooleanField(blank=False, default=False)
    paper_related_works_done = models.BooleanField(blank=False, default=False)
    paper_proposal_done = models.BooleanField(blank=False, default=False)
    paper_results_done = models.BooleanField(blank=False, default=False)
    paper_figures_done = models.BooleanField(blank=False, default=False)
    paper_professors_revision_done = models.BooleanField(blank=False, default=False)
    

events/forms.py
from django import forms
from events.models import Event
from bootstrap_datepicker_plus import DatePickerInput

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ("is_done", )

    name = forms.CharField(
        label="Event Name",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Event Name"}
        ),
    )

    url = forms.CharField(
        label="Event URL",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Event URL"}
        ),
    )

    qualis = forms.CharField(
        label="Qualis", widget=forms.Select(choices=Event.QUALIS_CHOICES)
    )

    type = forms.CharField(
        label="Type", widget=forms.Select(choices=Event.TYPE_CHOICES)
    )

    deadline = forms.DateField(
        required=True, label="Deadline", widget=DatePickerInput(format="%Y-%m-%d")
    )

events/views.py
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

# custom imports
from events.models import Event
from users.models import Student
from submissions.models import Submission
from submissions.views import get_status_background
from events.forms import EventForm
from datetime import datetime


def event_detail(request, pk, template_name="events/event_detail.html"):

    try:
        event = Event.objects.get(pk=pk)
    except Event.DoesNotExist:
        raise Http404("This Event does not exist :0")
    
    
    submissions = Submission.objects.filter(event=event)
    event = get_events_context(event)

    for sub in submissions:
        sub.status_background = get_status_background(sub.status)
    
    context = {"event": event, "submissions": submissions}
    return render(request, template_name, context)


# @login_required (use this decorator if deadlines must be seen only by users)
def event_list(request, template_name="events/event_list.html"):
    events = Event.objects.all()
    context = {}

    events = [get_events_context(t) for t in events]

    context["current_events"], context["past_events"] = filter_events(events)

    return render(request, template_name, context)


@login_required
def event_create(request, template_name="events/event_form.html"):
    form = EventForm(request.POST or None)

    if form.is_valid():
        event = form.save(commit=False)
        event.user = request.user
        event.save()
        return redirect("events:event_list")

    return render(request, template_name, {"form": form})


@login_required
def event_update(request, pk, template_name="events/event_form.html"):
    if request.user.is_superuser:
        event = get_object_or_404(Event, pk=pk)
    else:
        event = get_object_or_404(Event, pk=pk)
    form = EventForm(request.POST or None, instance=event)

    if form.is_valid():
        form.save()
        return redirect(f"/events/{pk}")

    return render(request, template_name, {"form": form})


@login_required
def event_delete(request, pk, template_name="events/event_confirm_delete.html"):
    if request.user.is_superuser:
        event = get_object_or_404(Event, pk=pk)
    else:
        event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        event.delete()
        return redirect("events:event_list")
    return render(request, template_name, {"object": event})


# Auxiliar methods:
def filter_events(events):
    """ 
    This method filter Event instances in two categories
    current events and past event, depending on the days_left field
     """
    current_events = list(filter(lambda t: (t.days_left >= 0), events))
    past_events = list(filter(lambda t: (t.days_left < 0), events))

    return current_events, past_events

def get_events_context(event):
    '''
    Some context is required for each Event
    '''
    event.days_left = get_days_left(event.deadline)
    return event

def get_days_left(deadline):
    """ Used to calculate how many days are left until a event deadline """
    now = datetime.now().date()
    days_left = (deadline - now).days
    return days_left

events/templates/events/event_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'events:event_list' %}">Event</a>: Delete?</h2>

<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <div class="form-group">
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
</form>

{% endblock %}

events/templates/events/event_detail.html
{% extends "base.html" %}
{% load mathfilters %}
{% block content %}
<!-- Event info -->

<div class="jumbotron">
  <h2 class="display-4">{{ event.name }}</h2>
  <br>
  <h4 class="display-8">
    {{ event.days_left|abs }} days {% if event.days_left >= 0 %} until deadline {% else %} past since deadline {% endif %} at {{ event.deadline }}
  </h4>
  <h4><a href="{{ event.url }}" target="_blank">Event URL</a></h4>
  <p class="lead">Type: {{event.get_type_display}}</p>
  <hr class="my-4">
  <h4 class="display-8">Submissions on this event:</h4>

  <!-- Submissions of this event -->
  <ul class="list-group list-group-flush my-4">
    {% for submission in submissions %}
      <li class="list-group-item ">
        <a href="{% url 'submissions:submission_detail' submission.id %}"> {{ submission.paper_acronym }} </a><span class="badge badge-{{submission.status_background}}">{{ submission.get_status_display }}</span>
      </li>
    {% empty %}
      <li  class="list-group-item">
        No current submissions on this event
      </li>
    {% endfor %}
  </ul>
  <div class="my-4">
    <a class="btn btn-info" href="{% url 'events:event_update' event.id %}" role="button">Edit</a>
    <a class="btn btn-danger" href="{% url 'events:event_delete' event.id %}" role="button">Delete</a>
    <a class="btn btn-primary" href="{% url 'submissions:submission_new' event.id %}" role="button">Add new submission</a>
  </div>
</div>

{% endblock %}

events/templates/events/event_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    {{ form.media }}

    <form method="post" class="form">
        <h2>
            <a href="{% url 'events:event_list' %}">
                Event
            </a>: Edit
        </h2>

        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

events/templates/events/event_list.html
{% extends "base.html" %}
{% load mathfilters %}
{% load static %}
{% block content %}

<!-- Current Events -->
<h1>Current Events</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Event</th>
            <th scope="col">Days Left</th>
            <th scope="col">Deadline</th>
            <th scope="col">Qualis</th>
        </tr>
    </thead>
    <tbody>
        {% for event in current_events %}
        <tr>
            <th scope="row"><a href="{% url 'events:event_detail' event.id %}">{{ event.name }}</a></th>
            <td>{{ event.days_left }}</td>
            <td>{{ event.deadline }}</td>
            <td>{{ event.qualis }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'events:event_new' %}" class="btn btn-success float-right">New Event</a>


<hr class="my-5">


<!-- Past Events -->
<h1>Past Events</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Event</th>
            <th scope="col">Days Passed</th>
            <th scope="col">Deadline</th>
            <th scope="col">Qualis</th>
        </tr>
    </thead>
    <tbody>
        {% for event in past_events %}
        <tr>
            <th scope="row"><a href="{% url 'events:event_detail' event.id %}">{{ event.name }}</a></th>
            <td>{{ event.days_left|abs }}</td> <!-- This is acctually a DAYS PASSED field -->
            <td>{{ event.deadline }}</td>
            <td>{{ event.qualis }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<img src="{% static "images/deadlines-timeline.png" %}" alt="Deadlines Timeline" class="img-fluid my-5 w-75 mx-auto d-block""/>

<script>
    $(document).ready(function() {
        $('.table').DataTable({
            "order": [[ 1, "asc" ]],
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bInfo": false,
            "dom": '<lfp<t>i>',
            "bAutoWidth": true });
        });
</script>

{% endblock %}