apps/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views

# Custom imports
from users import views as user_views

app_name = "apps"

urlpatterns = [
    # main url's
    path("admin/", admin.site.urls),
    path("events/", include("events.urls", namespace="events")),
    path("submissions/", include("submissions.urls", namespace="submissions")),
    path("", include("events.urls", namespace="home")),
    # Registration and SignIn related
    path("register/", user_views.register, name="register"),
    path("login/", user_views.login_request, name="login"),
    path("logout/", user_views.logout_request, name="logout"),
    # Profile related
    path("profile/", user_views.show_profile, name="profile"),
    path("profile/edit/<int:pk>", user_views.student_update, name="edit_profile"),
    # Deactivation related
    path("deactivate/", user_views.deactivate, name="deactivate"),
    path("reactivate/", user_views.reactivate, name="reactivate"),
    # Password reset related
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<str:uidb64>/<str:token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("", views.event_list, name="event_list"),
    path("<int:pk>", views.event_detail, name="event_detail"),
    path("new", views.event_create, name="event_new"),
    path("edit/<int:pk>", views.event_update, name="event_update"),
    path("delete/<int:pk>", views.event_delete, name="event_delete"),
]

submissions/urls.py
from django.urls import path

from . import views

app_name = "submissions"

urlpatterns = [
    path("", views.submission_list, name="submission_list"),
    path("<int:pk>", views.submission_detail, name="submission_detail"),
    path("new/<int:event_pk>", views.submission_create, name="submission_new"),
    path("edit/<int:pk>", views.submission_update, name="submission_update"),
    path("delete/<int:pk>", views.submission_delete, name="submission_delete"),
    path("done/<int:pk>", views.submission_done, name="submission_done"),
    path("undone/<int:pk>", views.submission_undone, name="submission_undone"),
]

apps/templates/includes/navbar.html
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand">Tasks control</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'events:event_list' %}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'submissions:submission_list' %}">Submissions</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="https://tomato-timer.com/" target="_blank">Pomodoro Timer</a>
                </li>
            </ul>
        </div>
        <form class="form-inline my-2 my-lg-0">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-info" href="{% url 'profile' %}">{{ user.name }}</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                            </li>
                    {% else %}
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Log In</a>
                        </li>
                    {% endif %}
                </ul>
        </form>
    </nav>
    <!-- navbar -->