apps/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views

# Custom imports
from users import views as user_views

app_name = "apps"

urlpatterns = [
    # main url's
    path("admin/", admin.site.urls),
    path("events/", include("events.urls", namespace="events")),
    path("submissions/", include("submissions.urls", namespace="submissions")),
    path("", include("events.urls", namespace="home")),
    # Registration and SignIn related
    path("register/", user_views.register, name="register"),
    path("login/", user_views.login_request, name="login"),
    path("logout/", user_views.logout_request, name="logout"),
    # Profile related
    path("profile/", user_views.show_profile, name="profile"),
    path("profile/edit/<int:pk>", user_views.student_update, name="edit_profile"),
    # Deactivation related
    path("deactivate/", user_views.deactivate, name="deactivate"),
    path("reactivate/", user_views.reactivate, name="reactivate"),
    # Password reset related
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<str:uidb64>/<str:token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("", views.event_list, name="event_list"),
    path("<int:pk>", views.event_detail, name="event_detail"),
    path("new", views.event_create, name="event_new"),
    path("edit/<int:pk>", views.event_update, name="event_update"),
    path("delete/<int:pk>", views.event_delete, name="event_delete"),
]

submissions/urls.py
from django.urls import path

from . import views

app_name = "submissions"

urlpatterns = [
    path("", views.submission_list, name="submission_list"),
    path("<int:pk>", views.submission_detail, name="submission_detail"),
    path("new/<int:event_pk>", views.submission_create, name="submission_new"),
    path("edit/<int:pk>", views.submission_update, name="submission_update"),
    path("delete/<int:pk>", views.submission_delete, name="submission_delete"),
    path("done/<int:pk>", views.submission_done, name="submission_done"),
    path("undone/<int:pk>", views.submission_undone, name="submission_undone"),
]

submissions/models.py
from django.db import models
from users.models import Student
from events.models import Event
from apps.models import ModelWithTimeStamp

class Submission(ModelWithTimeStamp):
    ''' This model stores informations about academic event submissions '''
    STATUS_CHOICES = (
        ('0', "In Writting Process"),
        ("1", "Not submitted"),
        ("2", "Under Revision"),
        ("3", "Accepted"),
        ("4", "Rejected"),
    )

    students = models.ManyToManyField(Student, blank=False, related_name='submissions')

    event = models.ForeignKey(Event, on_delete=models.SET_NULL,  null=True, related_name='submissions')

    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='0')

    paper_acronym = models.CharField(max_length=100, blank=False) 

    paper_url = models.CharField(max_length=400, blank=True, null=True)

    presentation_url = models.CharField(max_length=400, blank=True, null=True)

    rebuttal_url = models.CharField(max_length=400, blank=True, null=True)

    # Checklist fields ( related to the progress bar )
    implementation_done = models.BooleanField(blank=False, default=False)
    paper_introduction_done = models.BooleanField(blank=False, default=False)
    paper_related_works_done = models.BooleanField(blank=False, default=False)
    paper_proposal_done = models.BooleanField(blank=False, default=False)
    paper_results_done = models.BooleanField(blank=False, default=False)
    paper_figures_done = models.BooleanField(blank=False, default=False)
    paper_professors_revision_done = models.BooleanField(blank=False, default=False)
    

submissions/forms.py
from django import forms
from submissions.models import Submission
from events.models import Event
from users.models import Student


class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        exclude = ['event']
    
    # Students associated with this submission
    students = forms.ModelMultipleChoiceField(
        label='Select the students associated with this submission',
        queryset=Student.objects.filter(is_active=True),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    # Submission status 
    status = forms.CharField(
        label="Submission status", widget=forms.Select(choices=Submission.STATUS_CHOICES)
    )

    # Paper url
    paper_url = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'special'}))

    # Paper Acornym
    paper_acronym = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'special'}))



class EditSubmissionForm(SubmissionForm):
    class Meta:
        model = Submission
        fields = '__all__'

submissions/views.py
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

# Custom imports
from submissions.models import Submission
from submissions.forms import SubmissionForm, EditSubmissionForm
from users.models import Student
from events.models import Event



def submission_detail(request, pk, template_name="submissions/submission_detail.html"):

    try:
        submission = Submission.objects.get(pk=pk)
    except Submission.DoesNotExist:
        raise Http404("This submission does not exist :0")

    submission = get_aditional_info(submission)

    context = {
        'submission': submission,
        "students": submission.students.all(),
    }

    return render(request, template_name, context)


@login_required
def submission_list(request, template_name="submissions/submission_list.html"):
    
    current_submissions, past_submissions = get_submissions_and_context()
    n_submitted, approval_rate = get_statistics()

    context = {
        'past_submissions': past_submissions,
        'current_submissions': current_submissions,
        'total_submissions':n_submitted,
        'approval_rate': approval_rate,
    }

    return render(request, template_name, context)
    

@login_required
def submission_create(request, event_pk, template_name="submissions/submission_form.html"):
    
    form = SubmissionForm(request.POST or None)
    event = Event.objects.get(id=event_pk)

    if request.POST:
        if form.is_valid():
            submission = form.save(commit=False)
            submission.user = request.user
            submission.event = event
            submission.save()
            form.save_m2m()
            new_submission_message = "Created submission successfully"
            messages.success(request, new_submission_message)
            return redirect("submissions:submission_list")
        else:
            for msg in form._errors:
                messages.error(request, f"{form._errors[msg]}")

    return render(request, template_name, {"form": form, "event":event})


@login_required
def submission_update(request, pk, template_name="submissions/submission_form.html"):
    if request.user.is_superuser:
        submission = get_object_or_404(Submission, pk=pk)
    else:
        submission = get_object_or_404(Submission, pk=pk)

    form = EditSubmissionForm(request.POST or None, instance=submission)

    if request.POST:
        if form.is_valid():
            form.save()
            return redirect(f"/submissions/{pk}")
        else:
            for msg in form._errors:
                messages.error(request, f"{form._errors[msg]}")

    return render(request, template_name, {"form": form})


@login_required
def submission_delete(request, pk, template_name="submissions/submission_confirm_delete.html"):
    submission = get_object_or_404(Submission, pk=pk)
    
    if request.method == "POST":
        submission.delete()
        delete_message = "Successfully deleted that submission ;)"
        messages.success(request, delete_message)

        return redirect("submissions:submission_list")

    return render(request, template_name, {"submission": submission})


@login_required
def submission_done(request, pk):
    if request.user.is_superuser:
        submission = get_object_or_404(Submission, pk=pk)
    else:
        event = get_object_or_404(Submission, pk=pk, students=request.user)
    submission.submitted = True
    submission.save()
    return redirect(f"/submissions/{pk}")

@login_required
def submission_undone(request, pk):
    if request.user.is_superuser:
        submission = get_object_or_404(Submission, pk=pk)
    else:
        submission = get_object_or_404(Submission, pk=pk, students=request.user)
    submission.submitted = False
    submission.save()
    return redirect(f"/submissions/{pk}")


def get_submissions_and_context(student_id=None):
    """ Separate submissions according to their status and get their aditional info """
    current_status = [0,1,2]
    past_status = [3,4]

    if student_id:
        current_submissions = Submission.objects.filter(students=student_id).exclude(status__in=current_status)
        past_submissions = Submission.objects.filter(students=student_id).exclude(status__in=past_status)
    else:
        current_submissions = Submission.objects.filter(status__in=current_status)
        past_submissions = Submission.objects.filter(status__in=past_status)

    for submission in current_submissions:
        submission = get_aditional_info(submission)
    
    for submission in past_submissions:
        submission = get_aditional_info(submission)

    return current_submissions, past_submissions

def get_aditional_info(submission):
    """ Used to get aditional info for a submission
        currently aditional info includes:
        - progress bar percentage of submission completion 
        - progress bar background color
        - status background color
    """
    submission.progress_percentage = get_progress_percentage(submission)
    submission.status_background = get_status_background(submission.status)
    submission.progress_background = get_progress_background(submission.progress_percentage)

    return submission

def get_statistics():
    ''' This method get some statistics on the Submission instances '''
    # Only submission with status__in the values below are accounted for statistics
    n_submitted = Submission.objects.filter(status__in=[3,4]).count()
    n_approved = Submission.objects.filter(status=3).count()
    approval_rate = 0
    if n_submitted > 0:
        approval_rate =  n_approved // n_submitted *100
    return n_submitted, approval_rate


def get_status_background(status):
    """
    Gets the appropriate button color for a given status of a submission
    :param progress: The current status of a submission instance, check Submission model for choices field
    :return: a string representing the corresponding button
    """
    color = ""
    status = int(status)
    if status == 0 or status == 1:
        color = "light"
    elif status == 2:
        color = "warning"
    elif status == 3:
        color = "success"
    elif status ==4:
        color = "danger"
    else:
        color = "light"

    return color

def get_progress_background(progress):
    """
    Gets the appropriate background color for a given amount of progress made in a submission
    :param progress: the amount of progress between the start date and the ending date (0-100)
    :return: a string representing the corresponding color for a background with the given amount of progress
    """
    if progress == 100:
        color = "success"
    elif progress >= 65 and progress < 100:
        color = "warning"
    elif progress < 65:
        color = "danger"
    else:
        color = "danger"

    return color

def get_progress_percentage(submission):
    ''' Given the checklist of a submission 
    calculate how much of it is completed '''
    progress_percentage = 0

    if submission.get_status_display() == "Accepted":
        progress_percentage = 100
        return progress_percentage
    else:
        progress_percentage += 25 if submission.implementation_done else 0
        progress_percentage += 10 if submission.paper_introduction_done else 0
        progress_percentage += 10 if submission.paper_related_works_done else 0
        progress_percentage += 10 if submission.paper_proposal_done else 0
        progress_percentage += 10 if submission.paper_results_done else 0
        progress_percentage += 25 if submission.paper_figures_done else 0
        progress_percentage += 10 if submission.paper_professors_revision_done else 0

    return progress_percentage

submissions/templates/submissions/submission_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'submissions:submission_list' %}">Submission</a>: Delete?</h2>

<form method="post">
    {% csrf_token %}
    Are you sure you want to delete the submission for "{{ submission.event.name }}" ?<br/>
    <div class="form-group">
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
</form>

{% endblock %}

submissions/templates/submissions/submission_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Submission Details -->

<div class="jumbotron">
  <!--paper acronym-->
  <h2 class="display-4"> {{ submission.paper_acronym }}</h2>
  <br>
  <!--event name and submission status-->
  <h4 class="display-8">A submission for <strong>{{ submission.event.name|truncatechars:20 }}</strong> | <span class="badge badge-{{submission.status_background}}">{{ submission.get_status_display }}</span> </h4>
  <br>

  <!-- Progress bar-->
  {% include "submissions/includes/progress_bar.html" %}

  <!-- Checklist for this submission -->
  {% include "submissions/includes/checklist.html" %}

  <!-- Row with three cards -->
  <div class="card-deck">
    <!--card 1: paper url-->
    <div class="card">
      <a href="{{ submission.paper_url }}">
      <div class="card-body">
        <h5 class="card-title">Paper on Overleaf</h5>
        <p class="card-text">Papers are preferably written using Overleaf. Here you can check the paper pdf and source code.</p>
        <p class="card-text"><small class="text-muted">You may need the authors' permission to see this</small></p>
      </div>
    </a>
    </div>

    {% if submission.presentation_url %}
    <!--card 2: paper presentation-->
    <div class="card">
      <a href="{{ submission.presentation_url }}">
      <div class="card-body">
        <h5 class="card-title">Presentation Slides</h5>
        <p class="card-text">Here you can find the slides for the presentation of this sbumission</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </a>
    </div>
    {% endif %}

    <!--card 3: paper rebuttal-->
    {% if presentation.rebuttal_url %}
    <div class="card">
      <a href="{{ submission.rebuttal_url }}">
      <div class="card-body">
        <h5 class="card-title">Rebttal</h5>
        <p class="card-text">Rebuttal is the feedback text from the submission reviwers</p>
      </div>
    </a>
    </div>
    {% endif %}
    
  </div>
  

  <hr class="my-4" style="color:grey;">

  <!-- Students of this Submission -->
  <h4 class="display-8">Students working on this submission:</h4>
  <div class="col-sm">
    <ul class="list-group list-group-flush">
      {% for student in students %}
      <li class="list-group-item" style="background-color: transparent">
        <h6> {{ student.name }} </h6>
      </li>
      {% endfor %}
    </ul>
  </div>
  
  <!-- Edit and Delete buttons -->
  <div class="float-right alter-buttons">
    <a class="btn btn-outline-warning btn-md mx-1" href="{% url 'submissions:submission_update' submission.id %}" role="button">Edit</a>
    <a class="btn btn-outline-danger btn-md mx-1" href="{% url 'submissions:submission_delete' submission.id %}" role="button">Delete</a>
  </div>
</div>

{% endblock %}

submissions/templates/submissions/submission_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <form method="post" class="form">
        <h2>Creating/Editing a new submission for {{ event.name }}</h2>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

submissions/templates/submissions/submission_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Current submissions -->
<h1>Submissions</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Paper Acronym</th>
            <th scope="col">Event</th>
            <th scope="col">Status</th>
            <th scope="col">Progress bar</th>

        </tr>
    </thead>
    <tbody>
        {% for submission in current_submissions %}
        <tr>
            <th scope="row"><a href="{% url 'submissions:submission_detail' submission.id %}">{{ submission.paper_acronym|truncatechars:50 }}</a></th>
            <th scope="row"><a href="{% url 'events:event_detail' submission.event.id %}">{{ submission.event.name }}</a></th>
            <td><span class="badge badge-{{submission.status_background}}">{{ submission.get_status_display }}</span></td>
            <td>{% include "submissions/includes/progress_bar.html" %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<hr class="my-5">

<!-- Past submissions -->
<h1>Past Submissions</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Paper Acronym</th>
            <th scope="col">Event</th>
            <th scope="col">Status</th>
            <th scope="col">Progress bar</th>
        </tr>
    </thead>
    <tbody>
        {% for submission in past_submissions %}
        <tr>
            <th scope="row"><a href="{% url 'submissions:submission_detail' submission.id %}">{{ submission.paper_acronym|truncatechars:50 }}</a></th>
            <th scope="row"><a href="{% url 'events:event_detail' submission.event.id %}">{{ submission.event.name }}</a></th>
            <td><span class="badge badge-{{submission.status_background}}">{{ submission.get_status_display }}</span></td>
            <td>{% include "submissions/includes/progress_bar.html" %}</td>
            
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Submissions statistics card-->

<div class="card my-5" style="width: 18rem;  float: right;">
    <div class="card-body">
      <h5 class="card-title">Statistics</h5>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Total Submissions: {{ total_submissions }}</li>
        <li class="list-group-item">Approval Rate: {{ approval_rate }}%</li>
      </ul>
    </div>
  </div>

  <script>
    $(document).ready(function() {
        $('.table').DataTable({
            "order": [[ 1, "asc" ]],
            "bPaginate": false,
            "bLengthChange": false,
            "bFilter": true,
            "bInfo": false,
            "bAutoWidth": false });
        });
</script>
{% endblock %}